### ISSUE TITLE
OpenMRS frontend Login issue

### ISSUE THREAD

**Issue by kipyegonline** [openmrs/openmrs-esm-patient-management#806]
Hello OpenMRS support
A while ago i could login to openMRS swiftly with given username/password but lately its been throwing Error "Invalid username/password". 
then on reseting password I am hit with  invalid csrf token... I havent found a definitive solution online; i have cleared cached but the error persisits.... what could be the issue? browsers restring cookies?
My 2 questions:
1. Where is this session being fetched from? since i want to implement mine on a cloud service. Is it from the Open MRS Core?
2. Where do i set up an instance so that i can set up fields for patient registration? is it outside the project or hard coding directly on defaults.

PS: I find your docs to be abit difficult to start with
 Kindly advise

**Comment by ibacher** [comment]
Please don't report this as an issue against a repository. Please either take this up on talk.openmrs.org or the Slack instance.
